// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envelopewrapper.proto

package bft.miguel.proto;

public final class Envelopewrapper {
  private Envelopewrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnvelopeWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.EnvelopeWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string channelId = 1;</code>
     */
    java.lang.String getChannelId();
    /**
     * <code>string channelId = 1;</code>
     */
    com.google.protobuf.ByteString
        getChannelIdBytes();

    /**
     * <code>.common.Envelope envelope = 2;</code>
     */
    boolean hasEnvelope();
    /**
     * <code>.common.Envelope envelope = 2;</code>
     */
    org.hyperledger.fabric.protos.common.Common.Envelope getEnvelope();
    /**
     * <code>.common.Envelope envelope = 2;</code>
     */
    org.hyperledger.fabric.protos.common.Common.EnvelopeOrBuilder getEnvelopeOrBuilder();

    /**
     * <code>int64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
     */
    int getEnvelopeTypeValue();
    /**
     * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
     */
    bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType getEnvelopeType();
  }
  /**
   * Protobuf type {@code proto.EnvelopeWrapper}
   */
  public  static final class EnvelopeWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.EnvelopeWrapper)
      EnvelopeWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvelopeWrapper.newBuilder() to construct.
    private EnvelopeWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvelopeWrapper() {
      channelId_ = "";
      envelopeType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnvelopeWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              channelId_ = s;
              break;
            }
            case 18: {
              org.hyperledger.fabric.protos.common.Common.Envelope.Builder subBuilder = null;
              if (envelope_ != null) {
                subBuilder = envelope_.toBuilder();
              }
              envelope_ = input.readMessage(org.hyperledger.fabric.protos.common.Common.Envelope.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(envelope_);
                envelope_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              timestamp_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              envelopeType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bft.miguel.proto.Envelopewrapper.internal_static_proto_EnvelopeWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bft.miguel.proto.Envelopewrapper.internal_static_proto_EnvelopeWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.class, bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.EnvelopeWrapper.EnvelopeType}
     */
    public enum EnvelopeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NORMAL = 0;</code>
       */
      NORMAL(0),
      /**
       * <code>CONFIG = 1;</code>
       */
      CONFIG(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NORMAL = 0;</code>
       */
      public static final int NORMAL_VALUE = 0;
      /**
       * <code>CONFIG = 1;</code>
       */
      public static final int CONFIG_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EnvelopeType valueOf(int value) {
        return forNumber(value);
      }

      public static EnvelopeType forNumber(int value) {
        switch (value) {
          case 0: return NORMAL;
          case 1: return CONFIG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EnvelopeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EnvelopeType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EnvelopeType>() {
              public EnvelopeType findValueByNumber(int number) {
                return EnvelopeType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.getDescriptor().getEnumTypes().get(0);
      }

      private static final EnvelopeType[] VALUES = values();

      public static EnvelopeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EnvelopeType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.EnvelopeWrapper.EnvelopeType)
    }

    public static final int CHANNELID_FIELD_NUMBER = 1;
    private volatile java.lang.Object channelId_;
    /**
     * <code>string channelId = 1;</code>
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelId_ = s;
        return s;
      }
    }
    /**
     * <code>string channelId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENVELOPE_FIELD_NUMBER = 2;
    private org.hyperledger.fabric.protos.common.Common.Envelope envelope_;
    /**
     * <code>.common.Envelope envelope = 2;</code>
     */
    public boolean hasEnvelope() {
      return envelope_ != null;
    }
    /**
     * <code>.common.Envelope envelope = 2;</code>
     */
    public org.hyperledger.fabric.protos.common.Common.Envelope getEnvelope() {
      return envelope_ == null ? org.hyperledger.fabric.protos.common.Common.Envelope.getDefaultInstance() : envelope_;
    }
    /**
     * <code>.common.Envelope envelope = 2;</code>
     */
    public org.hyperledger.fabric.protos.common.Common.EnvelopeOrBuilder getEnvelopeOrBuilder() {
      return getEnvelope();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int ENVELOPETYPE_FIELD_NUMBER = 4;
    private int envelopeType_;
    /**
     * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
     */
    public int getEnvelopeTypeValue() {
      return envelopeType_;
    }
    /**
     * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
     */
    public bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType getEnvelopeType() {
      @SuppressWarnings("deprecation")
      bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType result = bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType.valueOf(envelopeType_);
      return result == null ? bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getChannelIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, channelId_);
      }
      if (envelope_ != null) {
        output.writeMessage(2, getEnvelope());
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      if (envelopeType_ != bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType.NORMAL.getNumber()) {
        output.writeEnum(4, envelopeType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getChannelIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, channelId_);
      }
      if (envelope_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEnvelope());
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (envelopeType_ != bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType.NORMAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, envelopeType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bft.miguel.proto.Envelopewrapper.EnvelopeWrapper)) {
        return super.equals(obj);
      }
      bft.miguel.proto.Envelopewrapper.EnvelopeWrapper other = (bft.miguel.proto.Envelopewrapper.EnvelopeWrapper) obj;

      if (!getChannelId()
          .equals(other.getChannelId())) return false;
      if (hasEnvelope() != other.hasEnvelope()) return false;
      if (hasEnvelope()) {
        if (!getEnvelope()
            .equals(other.getEnvelope())) return false;
      }
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (envelopeType_ != other.envelopeType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANNELID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
      if (hasEnvelope()) {
        hash = (37 * hash) + ENVELOPE_FIELD_NUMBER;
        hash = (53 * hash) + getEnvelope().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + ENVELOPETYPE_FIELD_NUMBER;
      hash = (53 * hash) + envelopeType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bft.miguel.proto.Envelopewrapper.EnvelopeWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.EnvelopeWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.EnvelopeWrapper)
        bft.miguel.proto.Envelopewrapper.EnvelopeWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bft.miguel.proto.Envelopewrapper.internal_static_proto_EnvelopeWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bft.miguel.proto.Envelopewrapper.internal_static_proto_EnvelopeWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.class, bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.Builder.class);
      }

      // Construct using bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channelId_ = "";

        if (envelopeBuilder_ == null) {
          envelope_ = null;
        } else {
          envelope_ = null;
          envelopeBuilder_ = null;
        }
        timestamp_ = 0L;

        envelopeType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bft.miguel.proto.Envelopewrapper.internal_static_proto_EnvelopeWrapper_descriptor;
      }

      @java.lang.Override
      public bft.miguel.proto.Envelopewrapper.EnvelopeWrapper getDefaultInstanceForType() {
        return bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public bft.miguel.proto.Envelopewrapper.EnvelopeWrapper build() {
        bft.miguel.proto.Envelopewrapper.EnvelopeWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public bft.miguel.proto.Envelopewrapper.EnvelopeWrapper buildPartial() {
        bft.miguel.proto.Envelopewrapper.EnvelopeWrapper result = new bft.miguel.proto.Envelopewrapper.EnvelopeWrapper(this);
        result.channelId_ = channelId_;
        if (envelopeBuilder_ == null) {
          result.envelope_ = envelope_;
        } else {
          result.envelope_ = envelopeBuilder_.build();
        }
        result.timestamp_ = timestamp_;
        result.envelopeType_ = envelopeType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bft.miguel.proto.Envelopewrapper.EnvelopeWrapper) {
          return mergeFrom((bft.miguel.proto.Envelopewrapper.EnvelopeWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bft.miguel.proto.Envelopewrapper.EnvelopeWrapper other) {
        if (other == bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.getDefaultInstance()) return this;
        if (!other.getChannelId().isEmpty()) {
          channelId_ = other.channelId_;
          onChanged();
        }
        if (other.hasEnvelope()) {
          mergeEnvelope(other.getEnvelope());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.envelopeType_ != 0) {
          setEnvelopeTypeValue(other.getEnvelopeTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bft.miguel.proto.Envelopewrapper.EnvelopeWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bft.miguel.proto.Envelopewrapper.EnvelopeWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object channelId_ = "";
      /**
       * <code>string channelId = 1;</code>
       */
      public java.lang.String getChannelId() {
        java.lang.Object ref = channelId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string channelId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getChannelIdBytes() {
        java.lang.Object ref = channelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channelId = 1;</code>
       */
      public Builder setChannelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 1;</code>
       */
      public Builder clearChannelId() {
        
        channelId_ = getDefaultInstance().getChannelId();
        onChanged();
        return this;
      }
      /**
       * <code>string channelId = 1;</code>
       */
      public Builder setChannelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channelId_ = value;
        onChanged();
        return this;
      }

      private org.hyperledger.fabric.protos.common.Common.Envelope envelope_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.hyperledger.fabric.protos.common.Common.Envelope, org.hyperledger.fabric.protos.common.Common.Envelope.Builder, org.hyperledger.fabric.protos.common.Common.EnvelopeOrBuilder> envelopeBuilder_;
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public boolean hasEnvelope() {
        return envelopeBuilder_ != null || envelope_ != null;
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public org.hyperledger.fabric.protos.common.Common.Envelope getEnvelope() {
        if (envelopeBuilder_ == null) {
          return envelope_ == null ? org.hyperledger.fabric.protos.common.Common.Envelope.getDefaultInstance() : envelope_;
        } else {
          return envelopeBuilder_.getMessage();
        }
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public Builder setEnvelope(org.hyperledger.fabric.protos.common.Common.Envelope value) {
        if (envelopeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          envelope_ = value;
          onChanged();
        } else {
          envelopeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public Builder setEnvelope(
          org.hyperledger.fabric.protos.common.Common.Envelope.Builder builderForValue) {
        if (envelopeBuilder_ == null) {
          envelope_ = builderForValue.build();
          onChanged();
        } else {
          envelopeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public Builder mergeEnvelope(org.hyperledger.fabric.protos.common.Common.Envelope value) {
        if (envelopeBuilder_ == null) {
          if (envelope_ != null) {
            envelope_ =
              org.hyperledger.fabric.protos.common.Common.Envelope.newBuilder(envelope_).mergeFrom(value).buildPartial();
          } else {
            envelope_ = value;
          }
          onChanged();
        } else {
          envelopeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public Builder clearEnvelope() {
        if (envelopeBuilder_ == null) {
          envelope_ = null;
          onChanged();
        } else {
          envelope_ = null;
          envelopeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public org.hyperledger.fabric.protos.common.Common.Envelope.Builder getEnvelopeBuilder() {
        
        onChanged();
        return getEnvelopeFieldBuilder().getBuilder();
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      public org.hyperledger.fabric.protos.common.Common.EnvelopeOrBuilder getEnvelopeOrBuilder() {
        if (envelopeBuilder_ != null) {
          return envelopeBuilder_.getMessageOrBuilder();
        } else {
          return envelope_ == null ?
              org.hyperledger.fabric.protos.common.Common.Envelope.getDefaultInstance() : envelope_;
        }
      }
      /**
       * <code>.common.Envelope envelope = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.hyperledger.fabric.protos.common.Common.Envelope, org.hyperledger.fabric.protos.common.Common.Envelope.Builder, org.hyperledger.fabric.protos.common.Common.EnvelopeOrBuilder> 
          getEnvelopeFieldBuilder() {
        if (envelopeBuilder_ == null) {
          envelopeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.hyperledger.fabric.protos.common.Common.Envelope, org.hyperledger.fabric.protos.common.Common.Envelope.Builder, org.hyperledger.fabric.protos.common.Common.EnvelopeOrBuilder>(
                  getEnvelope(),
                  getParentForChildren(),
                  isClean());
          envelope_ = null;
        }
        return envelopeBuilder_;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int envelopeType_ = 0;
      /**
       * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
       */
      public int getEnvelopeTypeValue() {
        return envelopeType_;
      }
      /**
       * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
       */
      public Builder setEnvelopeTypeValue(int value) {
        envelopeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
       */
      public bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType getEnvelopeType() {
        @SuppressWarnings("deprecation")
        bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType result = bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType.valueOf(envelopeType_);
        return result == null ? bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
       */
      public Builder setEnvelopeType(bft.miguel.proto.Envelopewrapper.EnvelopeWrapper.EnvelopeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        envelopeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.EnvelopeWrapper.EnvelopeType envelopeType = 4;</code>
       */
      public Builder clearEnvelopeType() {
        
        envelopeType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.EnvelopeWrapper)
    }

    // @@protoc_insertion_point(class_scope:proto.EnvelopeWrapper)
    private static final bft.miguel.proto.Envelopewrapper.EnvelopeWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bft.miguel.proto.Envelopewrapper.EnvelopeWrapper();
    }

    public static bft.miguel.proto.Envelopewrapper.EnvelopeWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvelopeWrapper>
        PARSER = new com.google.protobuf.AbstractParser<EnvelopeWrapper>() {
      @java.lang.Override
      public EnvelopeWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvelopeWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvelopeWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvelopeWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public bft.miguel.proto.Envelopewrapper.EnvelopeWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EnvelopeWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EnvelopeWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025envelopewrapper.proto\022\005proto\032\014common.p" +
      "roto\"\276\001\n\017EnvelopeWrapper\022\021\n\tchannelId\030\001 " +
      "\001(\t\022\"\n\010envelope\030\002 \001(\0132\020.common.Envelope\022" +
      "\021\n\ttimestamp\030\003 \001(\003\0229\n\014envelopeType\030\004 \001(\016" +
      "2#.proto.EnvelopeWrapper.EnvelopeType\"&\n" +
      "\014EnvelopeType\022\n\n\006NORMAL\020\000\022\n\n\006CONFIG\020\001B\022\n" +
      "\020bft.miguel.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.hyperledger.fabric.protos.common.Common.getDescriptor(),
        }, assigner);
    internal_static_proto_EnvelopeWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_EnvelopeWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EnvelopeWrapper_descriptor,
        new java.lang.String[] { "ChannelId", "Envelope", "Timestamp", "EnvelopeType", });
    org.hyperledger.fabric.protos.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
